/* frizbee C API. Generated by cbindgen from bindings/frizbee-c; do not edit.
 *
 * Strings cross as frizbee_str_t (pointer + length) and are NOT validated as
 * UTF-8; passing invalid UTF-8 is undefined behavior. Buffers returned by
 * frizbee must be released with the matching frizbee_*_free function, never
 * with free(). A matcher is not thread-safe: use one per thread or lock.
 *
 * There are no error codes: the API cannot fail on valid input. Two
 * pathological inputs panic and abort the process: more than UINT32_MAX
 * haystacks, which would overflow the match index, and a single haystack of
 * 4 GiB or more matched through frizbee_match_list_indices, whose byte
 * offsets would overflow the uint32_t indices. */

#ifndef FRIZBEE_H
#define FRIZBEE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum frizbee_case_matching_t {
  /**
   * Ignore case while matching
   */
  FRIZBEE_CASE_IGNORE = 0,
  /**
   * Ignore case unless the needle contains uppercase (default)
   */
  FRIZBEE_CASE_SMART,
  /**
   * Require matching bytes to have the same case
   */
  FRIZBEE_CASE_RESPECT,
} frizbee_case_matching_t;

typedef enum frizbee_unicode_matching_t {
  /**
   * Always match against bytes directly
   */
  FRIZBEE_UNICODE_IGNORE = 0,
  /**
   * Ignore unicode unless the needle contains a multi-byte unicode char
   * (default)
   */
  FRIZBEE_UNICODE_SMART,
  /**
   * Always use expensive unicode Smith Waterman for correctness across
   * multi-byte unicode chars in the haystack
   */
  FRIZBEE_UNICODE_ALWAYS,
} frizbee_unicode_matching_t;

/**
 * Selects the matching algorithm
 *
 * - `FRIZBEE_MATCHING_FUZZY` (default) uses the Smith-Waterman algorithm with
 *   typos, gaps and substitutions
 * - `FRIZBEE_MATCHING_EXACT` matches the haystack exactly
 * - `FRIZBEE_MATCHING_PREFIX` matches the haystack if it starts with the
 *   needle
 * - `FRIZBEE_MATCHING_SUFFIX` matches the haystack if it ends with the needle
 * - `FRIZBEE_MATCHING_SUBSTRING` matches the haystack if it contains the
 *   needle
 *
 * Only the `FRIZBEE_MATCHING_FUZZY` mode supports typos
 */
typedef enum frizbee_matching_t {
  /**
   * Smith-Waterman fuzzy matching with typos, gaps and substitutions
   * (default)
   */
  FRIZBEE_MATCHING_FUZZY = 0,
  /**
   * The haystack must equal the needle
   */
  FRIZBEE_MATCHING_EXACT,
  /**
   * The haystack must start with the needle
   */
  FRIZBEE_MATCHING_PREFIX,
  /**
   * The haystack must end with the needle
   */
  FRIZBEE_MATCHING_SUFFIX,
  /**
   * The needle must appear somewhere in the haystack. When it appears more
   * than once, the highest-scoring occurrence is used, preferring
   * earlier matches on tie
   */
  FRIZBEE_MATCHING_SUBSTRING,
} frizbee_matching_t;

typedef enum frizbee_sort_strategy_t {
  /**
   * Sort by descending score, then ascending haystack index (default)
   */
  FRIZBEE_SORT_SCORE_THEN_INDEX_ASC = 0,
  /**
   * Sort by descending score, then descending haystack index
   */
  FRIZBEE_SORT_SCORE_THEN_INDEX_DESC,
  /**
   * Sort by ascending haystack index, preserving input order
   */
  FRIZBEE_SORT_INDEX_ASC,
  /**
   * Sort by descending haystack index, reversing input order
   */
  FRIZBEE_SORT_INDEX_DESC,
} frizbee_sort_strategy_t;

/**
 * Primary entrypoint for fuzzy matching
 *
 * Opaque matcher handle, created by `frizbee_matcher_new` or
 * `frizbee_matcher_from_query` and destroyed by `frizbee_matcher_free`.
 *
 * This compiles the pattern once, allocates memory for the Smith Waterman
 * matrix, and reuses the selected SIMD backend.
 *
 * Ideally, only construct these at most once per list. They're cheap to
 * construct, but end up being expensive if you construct them for each item in
 * your list.
 *
 * Not thread-safe: use one matcher per thread or use external locking
 */
typedef struct frizbee_matcher_t frizbee_matcher_t;

/**
 * Controls the scoring used by the smith waterman algorithm. Pay close
 * attention to the documentation for each property, as small changes can lead
 * to poor matching.
 */
typedef struct frizbee_scoring_t {
  /**
   * Score for a matching character between needle and haystack
   */
  uint16_t match_score;
  /**
   * Penalty for a mismatch (substitution)
   */
  uint16_t mismatch_penalty;
  /**
   * Penalty for opening a gap (deletion/insertion)
   */
  uint16_t gap_open_penalty;
  /**
   * Penalty for extending a gap (deletion/insertion)
   */
  uint16_t gap_extend_penalty;
  /**
   * Bonus for matching the first character of the haystack (e.g. "h" on
   * "hello_world")
   */
  uint16_t prefix_bonus;
  /**
   * Bonus for matching a capital letter after a lowercase letter
   * (e.g. "b" on "fooBar" will receive a bonus on "B")
   */
  uint16_t capitalization_bonus;
  /**
   * Bonus for matching the case of the needle (e.g. "WorLd" on "WoRld" will
   * receive a bonus on "W", "o", "d")
   */
  uint16_t matching_case_bonus;
  /**
   * Bonus for matching the exact needle (e.g. "foo" on "foo" will receive
   * the bonus)
   */
  uint16_t exact_match_bonus;
  /**
   * Bonus for matching _after_ a delimiter character (e.g. "hw" on
   * "hello_world" will give a bonus on "w")
   */
  uint16_t delimiter_bonus;
} frizbee_scoring_t;

/**
 * Obtain defaults from `frizbee_config_default`
 *
 * The enum-valued fields are carried as plain `int32_t` so that out-of-range
 * values from C cannot cause undefined behavior; any value outside the named
 * constants falls back to that field's default
 */
typedef struct frizbee_config_t {
  /**
   * The maximum number of characters missing from the needle, before an item
   * in the haystack is filtered out. Negative means unlimited typos
   */
  int32_t max_typos;
  /**
   * Controls how case sensitivity/insensitivity is handled while matching.
   * One of the `frizbee_case_matching_t` values; anything else falls back to
   * `FRIZBEE_CASE_SMART`
   */
  int32_t casing;
  /**
   * Controls how unicode is handled while matching
   *
   * One of the `frizbee_unicode_matching_t` values. Anything else falls back
   * to `FRIZBEE_UNICODE_SMART`.
   */
  int32_t unicode;
  /**
   * Selects the matching algorithm: fuzzy (Smith-Waterman) or one of the
   * literal modes (exact, prefix, suffix, substring). Literal modes
   * require the needle to appear as a contiguous run of characters and
   * do not support typos (`max_typos` is ignored).
   *
   * One of the `frizbee_matching_t` values. Anything else falls back to
   * `FRIZBEE_MATCHING_FUZZY`.
   */
  int32_t matching;
  /**
   * Controls how results are ordered
   *
   * One of the `frizbee_sort_strategy_t` values. Anything else falls back to
   * `FRIZBEE_SORT_SCORE_THEN_INDEX_ASC`.
   */
  int32_t sort;
  /**
   * Controls the scoring used by the smith waterman algorithm. Pay close
   * attention to the documentation for each property, as small changes can
   * lead to poor matching.
   */
  struct frizbee_scoring_t scoring;
} frizbee_config_t;

/**
 * A borrowed string: `len` bytes at `ptr`, not necessarily null terminated.
 * The bytes MUST be valid UTF-8 as this is not validated.
 * `ptr` may be NULL only when `len` is 0.
 */
typedef struct frizbee_str_t {
  const char *ptr;
  size_t len;
} frizbee_str_t;

/**
 * Result of a fuzzy match, containing the score and index in the haystack
 */
typedef struct frizbee_match_t {
  uint16_t score;
  /**
   * Index of the match in the original list of haystacks
   */
  uint32_t index;
  /**
   * Matched the needle exactly (e.g. "foo" on "foo")
   */
  bool exact;
} frizbee_match_t;

/**
 * A list of matches owned by frizbee
 *
 * Release with `frizbee_matches_free`
 */
typedef struct frizbee_matches_t {
  struct frizbee_match_t *items;
  size_t len;
} frizbee_matches_t;

/**
 * Like `frizbee_match_t` but includes the indices of the chars in the haystack
 * that matched the needle in reverse order. Match `i` of
 * `frizbee_match_indices_list_t` owns
 * `indices[items[i].indices_start .. items[i].indices_start +
 * items[i].indices_len]`
 */
typedef struct frizbee_match_indices_t {
  uint16_t score;
  /**
   * Index of the match in the original list of haystacks
   */
  uint32_t index;
  /**
   * Matched the needle exactly (e.g. "foo" on "foo")
   */
  bool exact;
  /**
   * Start of this match's slice of the shared `indices` buffer
   */
  uint32_t indices_start;
  /**
   * Length of this match's slice of the shared `indices` buffer
   */
  uint32_t indices_len;
} frizbee_match_indices_t;

/**
 * A list of matches with indices, owned by frizbee. All matches share the one
 * `indices` buffer.
 *
 * Release with `frizbee_match_indices_list_free`
 */
typedef struct frizbee_match_indices_list_t {
  struct frizbee_match_indices_t *items;
  size_t len;
  uint32_t *indices;
  size_t indices_len;
} frizbee_match_indices_list_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the default configuration, mirroring `frizbee::Config::default()`
 */
struct frizbee_config_t frizbee_config_default(void);

/**
 * Needle length up to which scores are guaranteed to fit within the `uint16_t`
 * score. Longer needles still match, but their scores may saturate at
 * `UINT16_MAX`. `scoring` must not be NULL
 */
size_t frizbee_scoring_max_needle_len(const struct frizbee_scoring_t *scoring);

/**
 * Creates a matcher that matches `needle` literally (no query syntax); use
 * `frizbee_matcher_from_query` for query syntax and multi-pattern queries.
 * Never returns NULL. `config` must not be NULL. Destroy the matcher with
 * `frizbee_matcher_free`
 */
struct frizbee_matcher_t *frizbee_matcher_new(struct frizbee_str_t needle,
                                              const struct frizbee_config_t *config);

/**
 * Creates a matcher from a query of whitespace separated atoms, where special
 * syntax changes the matching mode: `foo` (fuzzy), `^foo` (prefix), `foo$`
 * (suffix), `'foo` (substring), `^foo$` (exact) and `!foo` (negated, substring
 * unless combined with the syntax above). A haystack matches when all of the
 * atoms match, summing each atom's score.
 *
 * Any special character can be escaped with a backslash, e.g. `\!foo` or
 * `foo\$` match the literal leading/trailing character, and `foo\ bar` matches
 * the literal space. Atoms with an empty needle, e.g. `!` or `^$`, are
 * dropped. Otherwise identical to `frizbee_matcher_new`
 */
struct frizbee_matcher_t *frizbee_matcher_from_query(struct frizbee_str_t query,
                                                     const struct frizbee_config_t *config);

/**
 * Destroys a matcher. NULL is a no-op
 */
void frizbee_matcher_free(struct frizbee_matcher_t *matcher);

/**
 * Matches `haystacks_len` haystacks against the matcher's pattern, returning
 * the matches ordered by the config's sort strategy. This API provides the
 * most performant path when matching on lists. The result is owned by frizbee:
 * release it with `frizbee_matches_free`
 */
struct frizbee_matches_t frizbee_match_list(struct frizbee_matcher_t *matcher,
                                            const struct frizbee_str_t *haystacks,
                                            size_t haystacks_len);

/**
 * Like `frizbee_match_list`, matching in parallel on `threads` real threads
 * (`0` = available CPU cores - 2). Threads work on 2048 item chunks, and the
 * final result is identical to the sequential version
 */
struct frizbee_matches_t frizbee_match_list_parallel(struct frizbee_matcher_t *matcher,
                                                     const struct frizbee_str_t *haystacks,
                                                     size_t haystacks_len,
                                                     size_t threads);

/**
 * Releases a match list returned by `frizbee_match_list` or
 * `frizbee_match_list_parallel` and zeroes it, so a second free is a no-op.
 * NULL is a no-op
 */
void frizbee_matches_free(struct frizbee_matches_t *matches);

/**
 * Matches a single haystack, returning whether it matched and writing the
 * match to `out` only when it did (`*out` is untouched otherwise).
 *
 * This API performs ~10% slower than the `frizbee_match_list` API. Consider
 * using `frizbee_match_list` if you have more than one haystack to match, as
 * it performs significantly better.
 */
bool frizbee_match_one(struct frizbee_matcher_t *matcher,
                       struct frizbee_str_t haystack,
                       uint32_t index,
                       struct frizbee_match_t *out);

/**
 * Like `frizbee_match_list`, but each match includes the indices of the chars
 * in the haystack that matched the needle (see `frizbee_match_indices_t` for
 * the layout). This API has not been optimized for performance, and should
 * only be used on small lists, e.g. the visible portion of results. Useful for
 * displaying matched indices in the UI. The result is owned by frizbee:
 * release it with `frizbee_match_indices_list_free`
 */
struct frizbee_match_indices_list_t frizbee_match_list_indices(struct frizbee_matcher_t *matcher,
                                                               const struct frizbee_str_t *haystacks,
                                                               size_t haystacks_len);

/**
 * Releases a list returned by `frizbee_match_list_indices` and zeroes it, so a
 * second free is a no-op. NULL is a no-op
 */
void frizbee_match_indices_list_free(struct frizbee_match_indices_list_t *matches);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FRIZBEE_H */
